name: Portfolio CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test-portfolio:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Docker Compose
        run: docker compose config

      - name: Start portfolio
        run: docker compose up -d

      - name: Wait for Nginx
        run: sleep 5

      - name: Test portfolio
        run: curl --fail http://localhost:8083

      - name: Show running containers
        run: docker compose ps

      - name: Stop portfolio
        if: always()
        run: docker compose down